package com.marketmaker.engine;

import com.marketmaker.model.Order;
import com.marketmaker.model.OrderType;
import com.marketmaker.model.Trade;

import java.util.ArrayList;
import java.util.Comparator;
import java.util.Iterator;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

/**
 * The demand-supply matching engine for the online produce market maker.
 *
 * The ledger is kept as two maps (per produce type): one holding open supply
 * orders, and one holding open demand orders. Whenever a new order arrives it
 * is immediately matched against the opposite ledger following these rules:
 *
 *   1. Priority is given to "lower supply price - higher demand price"
 *      matching, maximizing the market maker's spread.
 *   2. The supplier always receives the price they asked for, regardless of
 *      what the demand side offered.
 *   3. Within the same price, first-in-first-out (by arrival order) applies.
 *   4. A trade occurs whenever a demand price >= a supply price, and is
 *      recorded at the supply's price.
 *   5. Orders that cannot be fully satisfied remain in the ledger
 *      indefinitely (no expiry).
 *
 * This class is thread-agnostic (single-threaded use assumed per produce
 * ledger); callers running it concurrently should synchronize externally.
 */
public class MatchingEngine {

    // produce -> open supply orders for that produce
    private final Map<String, List<Order>> supplyLedger = new LinkedHashMap<>();
    // produce -> open demand orders for that produce
    private final Map<String, List<Order>> demandLedger = new LinkedHashMap<>();

    // Every order ever seen, keyed by order id - lets callers look up status/history.
    private final Map<String, Order> ordersById = new LinkedHashMap<>();

    /** Lowest price first, then earliest arrival first (FIFO tie-break). */
    private static final Comparator<Order> BY_PRICE_ASC_THEN_FIFO =
            Comparator.comparing(Order::getPrice).thenComparing(Order::getSequence);

    /** Highest price first, then earliest arrival first (FIFO tie-break). */
    private static final Comparator<Order> BY_PRICE_DESC_THEN_FIFO =
            Comparator.comparing(Order::getPrice).reversed().thenComparing(Order::getSequence);

    /**
     * Submits a new order to the ledger and immediately attempts to match it.
     *
     * @param order the incoming supply or demand order
     * @return the list of trades generated by this submission, in the order
     *         they occurred (may be empty if nothing could be matched yet)
     */
    public List<Trade> submit(Order order) {
        ordersById.put(order.getId(), order);
        if (order.getType() == OrderType.SUPPLY) {
            return matchSupplyOrder(order);
        } else {
            return matchDemandOrder(order);
        }
    }

    private List<Trade> matchSupplyOrder(Order supplyOrder) {
        List<Trade> trades = new ArrayList<>();
        List<Order> candidateDemands = demandLedger.computeIfAbsent(supplyOrder.getProduce(), p -> new ArrayList<>());
        candidateDemands.sort(BY_PRICE_DESC_THEN_FIFO);

        Iterator<Order> it = candidateDemands.iterator();
        while (supplyOrder.getRemainingQuantity() > 0 && it.hasNext()) {
            Order demand = it.next();
            // Demand orders are sorted highest-price-first: as soon as one
            // fails the "buy price >= sell price" test, none of the rest
            // (all lower or equal price) can match either, so we can stop.
            if (demand.getPrice().compareTo(supplyOrder.getPrice()) < 0) {
                break;
            }
            int matchedQty = Math.min(demand.getRemainingQuantity(), supplyOrder.getRemainingQuantity());
            trades.add(createTrade(demand, supplyOrder, matchedQty));
            demand.reduceQuantity(matchedQty);
            supplyOrder.reduceQuantity(matchedQty);
            if (demand.isFullyMatched()) {
                it.remove();
            }
        }

        if (!supplyOrder.isFullyMatched()) {
            supplyLedger.computeIfAbsent(supplyOrder.getProduce(), p -> new ArrayList<>()).add(supplyOrder);
        }
        return trades;
    }

    private List<Trade> matchDemandOrder(Order demandOrder) {
        List<Trade> trades = new ArrayList<>();
        List<Order> candidateSupplies = supplyLedger.computeIfAbsent(demandOrder.getProduce(), p -> new ArrayList<>());
        candidateSupplies.sort(BY_PRICE_ASC_THEN_FIFO);

        Iterator<Order> it = candidateSupplies.iterator();
        while (demandOrder.getRemainingQuantity() > 0 && it.hasNext()) {
            Order supply = it.next();
            // Supply orders are sorted lowest-price-first: once one is too
            // expensive for this demand, all remaining (equal/higher price)
            // are too, so we can stop scanning.
            if (supply.getPrice().compareTo(demandOrder.getPrice()) > 0) {
                break;
            }
            int matchedQty = Math.min(supply.getRemainingQuantity(), demandOrder.getRemainingQuantity());
            trades.add(createTrade(demandOrder, supply, matchedQty));
            supply.reduceQuantity(matchedQty);
            demandOrder.reduceQuantity(matchedQty);
            if (supply.isFullyMatched()) {
                it.remove();
            }
        }

        if (!demandOrder.isFullyMatched()) {
            demandLedger.computeIfAbsent(demandOrder.getProduce(), p -> new ArrayList<>()).add(demandOrder);
        }
        return trades;
    }

    private Trade createTrade(Order demand, Order supply, int quantity) {
        // Rule: trade is always recorded at the supply order's price.
        return new Trade(demand.getId(), supply.getId(), supply.getPrice(), quantity, java.time.LocalDateTime.now());
    }

    /** Looks up any order (supply or demand, open or fully matched) by id. */
    public Order getOrder(String orderId) {
        return ordersById.get(orderId);
    }

    /**
     * Wipes the entire in-memory ledger and order history — used by the
     * full-reset API ({@code DELETE /api/orders}) alongside clearing the
     * database, so the engine and the DB stay in sync after a reset.
     */
    public void reset() {
        supplyLedger.clear();
        demandLedger.clear();
        ordersById.clear();
    }

    /**
     * Removes an order from its produce ledger without changing its
     * quantities or status — used by PUT when editing a still-PENDING
     * order's price/quantity: pull it out, mutate it, then {@link #submit}
     * it again so it re-enters the ledger (if anything's left unmatched)
     * and gets a fresh chance to match under its new price/quantity.
     *
     * @return true if the order was found and removed from its ledger list
     */
    public boolean withdrawForUpdate(String orderId) {
        Order order = ordersById.get(orderId);
        if (order == null) {
            return false;
        }
        Map<String, List<Order>> ledger = order.getType() == OrderType.SUPPLY ? supplyLedger : demandLedger;
        List<Order> list = ledger.get(order.getProduce());
        return list != null && list.remove(order);
    }

    /**
     * Cancels an order's remaining (unmatched) quantity (used by DELETE) and
     * removes it from its ledger so it's no longer considered for future
     * matches. Quantity already matched into trades before this call is
     * untouched and remains part of trade history.
     *
     * @return the cancelled order, or {@code null} if the id is unknown
     */
    public Order cancelOrder(String orderId) {
        Order order = ordersById.get(orderId);
        if (order == null) {
            return null;
        }
        Map<String, List<Order>> ledger = order.getType() == OrderType.SUPPLY ? supplyLedger : demandLedger;
        List<Order> list = ledger.get(order.getProduce());
        if (list != null) {
            list.remove(order);
        }
        order.cancelRemaining();
        return order;
    }

    /** Re-hydrates the ledger with a previously-persisted, still-open order (used by Part 2 on startup). */
    public void loadExistingOpenOrder(Order order) {
        ordersById.put(order.getId(), order);
        if (order.getRemainingQuantity() <= 0) {
            return;
        }
        if (order.getType() == OrderType.SUPPLY) {
            supplyLedger.computeIfAbsent(order.getProduce(), p -> new ArrayList<>()).add(order);
        } else {
            demandLedger.computeIfAbsent(order.getProduce(), p -> new ArrayList<>()).add(order);
        }
    }
}
