package com.marketmaker.spring.dto;

import javax.validation.constraints.NotBlank;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Pattern;
import javax.validation.constraints.Positive;
import java.math.BigDecimal;

/**
 * Request body for {@code POST /api/orders/supply}.
 *
 * As of Part 4, the order id is auto-generated by the application (it is
 * returned in the response) rather than supplied by the client.
 *
 * Example:
 * <pre>
 * {
 *   "time": "09:45",
 *   "produce": "tomato",
 *   "price": 24,
 *   "quantity": 100
 * }
 * </pre>
 */
public class SupplyOrderRequest {

    @NotBlank(message = "time is required")
    @Pattern(regexp = "^([01]\\d|2[0-3]):[0-5]\\d$", message = "time must be in HH:mm format")
    private String time;

    @NotBlank(message = "produce is required")
    private String produce;

    @NotNull(message = "price is required")
    @Positive(message = "price must be positive")
    private BigDecimal price;

    @NotNull(message = "quantity is required")
    @Positive(message = "quantity must be positive")
    private Integer quantity;

    public String getTime() {
        return time;
    }

    public void setTime(String time) {
        this.time = time;
    }

    public String getProduce() {
        return produce;
    }

    public void setProduce(String produce) {
        this.produce = produce;
    }

    public BigDecimal getPrice() {
        return price;
    }

    public void setPrice(BigDecimal price) {
        this.price = price;
    }

    public Integer getQuantity() {
        return quantity;
    }

    public void setQuantity(Integer quantity) {
        this.quantity = quantity;
    }
}
