package com.marketmaker.spring.controller;

import com.marketmaker.spring.dto.DemandOrderRequest;
import com.marketmaker.spring.dto.OrderResponse;
import com.marketmaker.spring.dto.StatusResponse;
import com.marketmaker.spring.dto.SupplyOrderRequest;
import com.marketmaker.spring.dto.UpdateOrderRequest;
import com.marketmaker.spring.service.OrderService;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.DeleteMapping;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.PutMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

import javax.validation.Valid;

/**
 * Java Exercise 1 - Part 3/4 [Spring]: Web BE Application.
 *
 * Exposes the two required POST APIs for publishing supply and demand
 * orders, a status lookup API (Part 4), and two additional endpoints for
 * editing/cancelling an order: {@code PUT /api/orders/{orderId}} and
 * {@code DELETE /api/orders/{orderId}}. All delegate to {@link OrderService},
 * which persists the change, runs/re-runs it through the same
 * {@code MatchingEngine} used by Parts 1 & 2, and returns the resulting
 * order state + any trades generated. Order ids are auto-generated by the
 * application rather than supplied by the client.
 */
@RestController
@RequestMapping("/api/orders")
public class OrderController {

    private final OrderService orderService;

    public OrderController(OrderService orderService) {
        this.orderService = orderService;
    }

    /**
     * Publishes a new supply order (a farmer/trader offering produce). The
     * order id is auto-generated and returned in the response.
     *
     * Example request body:
     * <pre>
     * { "time": "09:45", "produce": "tomato", "price": 24, "quantity": 100 }
     * </pre>
     */
    @PostMapping("/supply")
    public ResponseEntity<OrderResponse> addSupplyOrder(@Valid @RequestBody SupplyOrderRequest request) {
        OrderResponse response = orderService.addSupplyOrder(request);
        return ResponseEntity.status(HttpStatus.CREATED).body(response);
    }

    /**
     * Publishes a new demand order (a customer/trader requesting produce).
     * The order id is auto-generated and returned in the response.
     *
     * Example request body:
     * <pre>
     * { "time": "09:47", "produce": "tomato", "price": 22, "quantity": 110 }
     * </pre>
     */
    @PostMapping("/demand")
    public ResponseEntity<OrderResponse> addDemandOrder(@Valid @RequestBody DemandOrderRequest request) {
        OrderResponse response = orderService.addDemandOrder(request);
        return ResponseEntity.status(HttpStatus.CREATED).body(response);
    }

    /**
     * Part 4: looks up the status of any previously submitted order (supply
     * or demand) by its id — whether it's still pending, partially filled,
     * or fully traded, plus the trades it's been part of.
     *
     * Example: {@code GET /api/orders/s1/status}
     */
    @GetMapping("/{orderId}/status")
    public ResponseEntity<StatusResponse> getOrderStatus(@PathVariable String orderId) {
        StatusResponse response = orderService.getOrderStatus(orderId);
        return ResponseEntity.ok(response);
    }

    /**
     * Edits an existing order's price and/or quantity, then immediately
     * re-attempts matching under the new values. Only allowed while the
     * order is still {@code PENDING} (nothing matched yet) — otherwise
     * returns {@code 409 Conflict}. Unknown order id returns {@code 404}.
     *
     * Example: {@code PUT /api/orders/s1} with body
     * <pre>
     * { "price": 23, "quantity": 80 }
     * </pre>
     */
    @PutMapping("/{orderId}")
    public ResponseEntity<OrderResponse> updateOrder(@PathVariable String orderId,
                                                      @Valid @RequestBody UpdateOrderRequest request) {
        OrderResponse response = orderService.updateOrder(orderId, request);
        return ResponseEntity.ok(response);
    }

    /**
     * Full reset: wipes every order and trade (database + in-memory ledger)
     * and restarts the auto-generated id counters at 1. Intended for testing
     * — lets you re-run a worked example from a clean slate without leaving
     * Postman to run manual SQL. Distinct from {@code DELETE /{orderId}}
     * (that cancels one order; this clears everything).
     *
     * Example: {@code DELETE /api/orders}
     */
    @DeleteMapping
    public ResponseEntity<Void> resetAll() {
        orderService.resetAll();
        return ResponseEntity.noContent().build();
    }

    /**
     * Cancels whatever quantity of an order is still unmatched. Quantity
     * already locked into trades before the call is untouched and stays in
     * trade history — the order's row isn't actually deleted (it can't be,
     * once trades reference it), it's marked {@code CANCELLED} instead.
     * Returns {@code 409 Conflict} if the order is already {@code FILLED}
     * or already {@code CANCELLED}; {@code 404} if the order id is unknown.
     *
     * Example: {@code DELETE /api/orders/s1}
     */
    @DeleteMapping("/{orderId}")
    public ResponseEntity<StatusResponse> cancelOrder(@PathVariable String orderId) {
        StatusResponse response = orderService.cancelOrder(orderId);
        return ResponseEntity.ok(response);
    }
}
